### PR TITLE
Feature/issue 322

### PR DESCRIPTION
**Pull request by Nizernizer**

### CODE REVIEW

**Comment by Nizernizer** [comment]
Do not merge branches until the server code pushes them. @exexute

**Review by exexute — COMMENTED** [review]
1. Why `projectVersion` is `AUTO_CREATE_PROJECT_VERSION`?
2. Is the design of the `RESPONSE_BODY_LENGTH_DEFAULT` value unreasonable?

**Comment by Nizernizer** [comment]
> 1. Why `projectVersion` is `AUTO_CREATE_PROJECT_VERSION`?
> 2. Is the design of the `RESPONSE_BODY_LENGTH_DEFAULT` value unreasonable?

Fixed and texted. Please review. @exexute

**Review by exexute — APPROVED** [review]
No objection to the code.

**Pull request merged**
